import type { Component } from 'vue';
import {
  CalendarIcon,
  ChartPieIcon,
  StarIcon,
  HomeIcon,
  UsersIcon,
  BanknotesIcon,
  ClockIcon,
  BuildingOfficeIcon,
  CalculatorIcon,
  WalletIcon,
  DocumentTextIcon,
  ChatBubbleBottomCenterTextIcon,
  ChartBarSquareIcon,
  AtSymbolIcon,
  TrophyIcon,
  CalendarDaysIcon,
  DocumentCurrencyEuroIcon,
  LanguageIcon,
  GlobeEuropeAfricaIcon,
  CurrencyEuroIcon,
  WrenchScrewdriverIcon,
  DocumentIcon,
  ArchiveBoxIcon,
  NewspaperIcon,
  QuestionMarkCircleIcon,
  CogIcon,
  PhotoIcon,
  ChatBubbleLeftRightIcon,
  AcademicCapIcon,
  GlobeAltIcon,
  CodeBracketIcon,
  ExclamationTriangleIcon,
  ShoppingCartIcon,
  HomeModernIcon,
  KeyIcon,
  SparklesIcon,
  SunIcon,
  Squares2X2Icon,
  BuildingOffice2Icon,
  RectangleStackIcon,
  FlagIcon,
  MapPinIcon,
  MapIcon,
  ChartBarIcon,
  UserGroupIcon,
  ScaleIcon,
} from '@heroicons/vue/24/outline';

export interface MenuSubItem {
  name: string;
  link: string;
  current: boolean;
}

export interface MenuLinkItem {
  key: string;
  name: string;
  icon: Component;
  current: boolean;
  link?: string;
  slug?: string;
  onlyUserId?: number;
  submenu?: MenuSubItem[];
}

export interface MenuSectionDef {
  key: string;
  title: string;
  menu: MenuLinkItem[];
}

export const menuSections: MenuSectionDef[] = [
  {
    key: 'home',
    title: 'Úvod',
    menu: [
      { key: 'home', name: 'Přehled', link: '/', icon: HomeIcon, current: true },
      {
        key: 'statistiky',
        name: 'Statistiky',
        link: '/statistiky',
        icon: ChartPieIcon,
        current: false,
        onlyUserId: 1,
      },
    ],
  },
  {
    key: 'content',
    title: 'Obsah',
    menu: [
      {
        key: 'posts',
        name: 'Blogové članky',
        icon: ArchiveBoxIcon,
        current: false,
        slug: 'posts',
        submenu: [
          {
            name: 'Články',
            link: '/obsah/clanky',
            current: false,
          },
          {
            name: 'Kategorie',
            link: '/obsah/clanky/kategorie',
            current: false,
          },
        ],
      },
      {
        key: 'obsah_stranky',
        name: 'Informační stránky',
        link: '/obsah/stranky',
        icon: DocumentIcon,
        current: false,
        slug: 'pages',
      },
      {
        key: 'obsah_bloky',
        name: 'Bloky',
        link: '/obsah/bloky',
        icon: RectangleStackIcon,
        current: false,
        slug: 'blocks',
      },
      {
        key: 'obsah_novinky',
        name: 'Novinky',
        link: '/obsah/novinky',
        icon: NewspaperIcon,
        current: false,
        slug: 'novelties',
      },
      {
        key: 'obsah_sluzby',
        name: 'Služby',
        icon: WrenchScrewdriverIcon,
        current: false,
        slug: 'services',
        submenu: [
          {
            name: 'Přehled',
            link: '/obsah/sluzby',
            current: false,
          },
          {
            name: 'Rezervace',
            link: '/obsah/sluzby/rezervace',
            current: false,
          },
        ],
      },
      {
        key: 'events',
        name: 'Události a akce',
        icon: CalendarDaysIcon,
        current: false,
        slug: 'events',
        submenu: [
          {
            name: 'Události',
            link: '/obsah/udalosti',
            current: false,
          },
          {
            name: 'Kategorie',
            link: '/obsah/udalosti/kategorie',
            current: false,
          },
          {
            name: 'Registrace',
            link: '/obsah/udalosti/registrace',
            current: false,
          },
        ],
      },
      {
        key: 'obsah_reference',
        name: 'Recenze',
        link: '/obsah/reference',
        icon: StarIcon,
        current: false,
        slug: 'reviews',
      },
      {
        key: 'obsah_loga',
        name: 'Loga klientů',
        link: '/obsah/loga',
        icon: PhotoIcon,
        current: false,
        slug: 'logos',
      },
      {
        key: 'obsah_fotogalerie',
        name: 'Fotogalerie',
        link: '/obsah/fotogalerie',
        icon: Squares2X2Icon,
        current: false,
        slug: 'photo_galleries',
      },
      {
        key: 'careers',
        name: 'Pracovní pozice',
        icon: AcademicCapIcon,
        current: false,
        slug: 'careers',
        submenu: [
          {
            name: 'Pracovní pozice',
            link: '/obsah/pracovni-pozice',
            current: false,
          },
          {
            name: 'Žádosti',
            link: '/obsah/pracovni-pozice/zadosti',
            current: false,
          },
        ],
      },
      {
        key: 'obsah_kvizy',
        name: 'Kvízy',
        link: '/obsah/kvizy',
        icon: QuestionMarkCircleIcon,
        current: false,
        slug: 'quizzes',
      },
      {
        key: 'faqs',
        name: 'FAQ',
        icon: ChatBubbleLeftRightIcon,
        current: false,
        slug: 'faqs',
        submenu: [
          {
            name: 'FAQ',
            link: '/obsah/faq',
            current: false,
          },
          {
            name: 'Kategorie',
            link: '/obsah/faq/kategorie',
            current: false,
          },
        ],
      },
    ],
  },
  {
    key: 'restaurant',
    title: 'Restaurace',
    menu: [
      {
        key: 'restaurace_alergeny',
        name: 'Alergeny',
        link: '/restaurace/alergeny',
        icon: ExclamationTriangleIcon,
        current: false,
        slug: 'allergens',
      },
      {
        key: 'foodstuffs',
        name: 'Potraviny',
        icon: ShoppingCartIcon,
        current: false,
        slug: 'foodstuffs',
        submenu: [
          {
            name: 'Potraviny',
            link: '/restaurace/potraviny',
            current: false,
          },
          {
            name: 'Kategorie potravin',
            link: '/restaurace/potraviny/kategorie',
            current: false,
          },
        ],
      },
      {
        key: 'meals',
        name: 'Jídla',
        icon: DocumentTextIcon,
        current: false,
        slug: 'meals',
        submenu: [
          {
            name: 'Jídla',
            link: '/restaurace/jidla',
            current: false,
          },
          {
            name: 'Kategorie jídel',
            link: '/restaurace/jidla/kategorie',
            current: false,
          },
        ],
      },
      {
        key: 'recipes',
        name: 'Recepty',
        icon: DocumentTextIcon,
        current: false,
        slug: 'recipes',
        submenu: [
          {
            name: 'Recepty',
            link: '/restaurace/recepty',
            current: false,
          },
          {
            name: 'Kategorie receptů',
            link: '/restaurace/recepty/kategorie',
            current: false,
          },
        ],
      },
      {
        key: 'menus',
        name: 'Jídelní lístky',
        icon: DocumentTextIcon,
        current: false,
        slug: 'menus',
        submenu: [
          {
            name: 'Jídelní lístky',
            link: '/restaurace/menu',
            current: false,
          },
          {
            name: 'Sekce lístku',
            link: '/restaurace/menu/sekce',
            current: false,
          },
        ],
      },
      {
        key: 'restaurace_kalkulacka',
        name: 'Kalorická kalkulačka',
        link: '/restaurace/kalkulacka',
        icon: CalculatorIcon,
        current: false,
        slug: 'calorie_measurements',
      },
      {
        key: 'restaurace_stoly',
        name: 'Stoly',
        link: '/restaurace/stoly',
        icon: BuildingOfficeIcon,
        current: false,
        slug: 'restaurant_tables',
      },
      {
        key: 'restaurace_rezervace',
        name: 'Rezervace',
        link: '/restaurace/rezervace',
        icon: CalendarDaysIcon,
        current: false,
        slug: 'reservations',
      },
    ],
  },
  {
    key: 'accommodation',
    title: 'Ubytování',
    menu: [
      {
        key: 'ubytovani_apartmany',
        name: 'Apartmány',
        link: '/ubytovani/apartmany',
        icon: HomeModernIcon,
        current: false,
        slug: 'apartments',
      },
      {
        key: 'ubytovani_typy_apartmanu',
        name: 'Typy apartmánů',
        link: '/ubytovani/typy-apartmanu',
        icon: Squares2X2Icon,
        current: false,
        slug: 'apartment_types',
      },
      {
        key: 'ubytovani_budovy',
        name: 'Budovy',
        link: '/ubytovani/budovy',
        icon: BuildingOffice2Icon,
        current: false,
        slug: 'buildings',
      },
      {
        key: 'ubytovani_vybaveni',
        name: 'Vybavení',
        link: '/ubytovani/vybaveni',
        icon: SparklesIcon,
        current: false,
        slug: 'amenities',
      },
      {
        key: 'ubytovani_rocni_obdobi',
        name: 'Roční období',
        link: '/ubytovani/rocni-obdobi',
        icon: SunIcon,
        current: false,
        slug: 'seasons',
      },
      {
        key: 'ubytovani_rezervace',
        name: 'Rezervace',
        link: '/ubytovani/rezervace',
        icon: KeyIcon,
        current: false,
        slug: 'apartment_reservations',
      },
    ],
  },
  {
    key: 'discgolf',
    title: 'Disc Golf',
    menu: [
      {
        key: 'discgolf_hriste',
        name: 'Hřiště',
        link: '/discgolf/hriste',
        icon: MapPinIcon,
        current: false,
        slug: 'courses',
      },
      {
        key: 'discgolf_hraci',
        name: 'Hráči',
        link: '/discgolf/hraci',
        icon: UserGroupIcon,
        current: false,
        slug: 'players',
      },
      {
        key: 'discgolf_hry',
        name: 'Hry',
        link: '/discgolf/hry',
        icon: FlagIcon,
        current: false,
        slug: 'games',
      },
      {
        key: 'discgolf_statistiky',
        name: 'Statistiky hráčů',
        link: '/discgolf/statistiky',
        icon: ChartBarIcon,
        current: false,
        slug: 'games',
      },
      {
        key: 'discgolf_statistiky_hriste',
        name: 'Statistiky hřišť',
        link: '/discgolf/statistiky-hriste',
        icon: MapIcon,
        current: false,
        slug: 'games',
      },
      {
        key: 'discgolf_pravidla',
        name: 'Pravidla',
        link: '/discgolf/pravidla',
        icon: ScaleIcon,
        current: false,
        slug: 'games',
      },
    ],
  },
  {
    key: 'customers',
    title: 'Zákazníci',
    menu: [
      {
        key: 'customers',
        name: 'Zákazníci',
        icon: UsersIcon,
        current: false,
        slug: 'customers',
        submenu: [
          {
            name: 'Zákazníci',
            link: '/zakaznici',
            current: false,
          },
          {
            name: 'Skupiny zákazníků',
            link: '/zakaznici/skupiny',
            current: false,
          },
        ],
      },
      {
        key: 'zakaznici_vouchery',
        name: 'Slevové vouchery',
        link: '/zakaznici/vouchery',
        icon: DocumentCurrencyEuroIcon,
        current: false,
        slug: 'vouchers',
      },
      {
        key: 'uzivatele_newslettery',
        name: 'Odběry newsletteru',
        link: '/uzivatele/newslettery',
        icon: AtSymbolIcon,
        current: false,
        slug: 'newsletters',
      },
      {
        key: 'uzivatele_poptavky',
        name: 'Poptávky',
        link: '/uzivatele/poptavky',
        icon: QuestionMarkCircleIcon,
        current: false,
        slug: 'demands',
      },
    ],
  },
  {
    key: 'business',
    title: 'Byznys a osobní růst',
    menu: [
      {
        key: 'contacts',
        name: 'Kontakty',
        icon: UsersIcon,
        current: false,
        slug: 'contacts',
        submenu: [
          {
            name: 'Kontakty',
            link: '/kontakty',
            current: false,
          },
          {
            name: 'Nástěnka',
            link: '/kontakty/nastenka',
            current: false,
          },
          {
            name: 'Seznamy kontaktů',
            link: '/kontakty/seznamy',
            current: false,
          },
          {
            name: 'Zdroje',
            link: '/kontakty/zdroje',
            current: false,
          },
          {
            name: 'Fáze',
            link: '/kontakty/faze',
            current: false,
          },
          {
            name: 'Úkoly',
            link: '/kontakty/ukoly',
            current: false,
          },
          {
            name: 'Hovory a schůzky',
            link: '/kontakty/hovory-schuzky',
            current: false,
          },
        ],
      },
      {
        key: 'aktivita',
        name: 'Aktivita',
        link: '/aktivita',
        icon: CalendarIcon,
        current: false,
        slug: 'users_has_activities',
      },
      {
        key: 'sablony_zprav',
        name: 'Šablony zpráv',
        link: '/sablony-zprav',
        icon: ChatBubbleBottomCenterTextIcon,
        current: false,
        slug: 'message_blueprints',
      },
      {
        key: 'business_kalendar',
        name: 'Kalendář',
        link: '/demo',
        icon: CalendarIcon,
        current: false,
        slug: 'calendars',
      },
      {
        key: 'cashflow',
        name: 'Cashflow',
        link: '/cashflow',
        icon: BanknotesIcon,
        current: false,
        slug: 'cashflows',
      },
      {
        key: 'business_ligy',
        name: 'Ligy',
        link: '/demo',
        icon: TrophyIcon,
        current: false,
        slug: 'leagues',
      },
    ],
  },
  {
    key: 'management',
    title: 'Vedení firmy',
    menu: [
      {
        key: 'klienti',
        name: 'Klienti',
        link: '/klienti',
        icon: BuildingOfficeIcon,
        current: false,
        slug: 'clients',
      },
      {
        key: 'faktury',
        name: 'Faktury',
        link: '/faktury',
        icon: WalletIcon,
        current: false,
        slug: 'invoices',
      },
      {
        key: 'projects',
        name: 'Projekty',
        icon: BuildingOfficeIcon,
        current: false,
        slug: 'projects',
        submenu: [
          {
            name: 'Projekty',
            link: '/projekty',
            current: false,
          },
          {
            name: 'Stavy projektů',
            link: '/projekty/stavy',
            current: false,
          },
        ],
      },
      {
        key: 'cenove_nabidky',
        name: 'Cenové nabídky',
        link: '/cenove-nabidky',
        icon: DocumentTextIcon,
        current: false,
        slug: 'price_offers',
      },
      {
        key: 'sledovani_casu',
        name: 'Sledování času',
        link: '/sledovani-casu',
        icon: ClockIcon,
        current: false,
        slug: 'project_time_entries',
      },
      {
        key: 'project_tasks',
        name: 'Úkoly',
        icon: ChartBarSquareIcon,
        current: false,
        slug: 'project_tasks',
        submenu: [
          {
            name: 'Přehled úkolů',
            link: '/ukoly',
            current: false,
          },
          {
            name: 'Boardy',
            link: '/ukoly/boardy',
            current: false,
          },
        ],
      },
      {
        key: 'employees',
        name: 'Zaměstnanci',
        icon: UsersIcon,
        current: false,
        slug: 'employees',
        submenu: [
          {
            name: 'Zaměstnanci',
            link: '/zamestnanci',
            current: false,
          },
          {
            name: 'Divize',
            link: '/zamestnanci/divize',
            current: false,
          },
        ],
      },
      {
        key: 'shifts',
        name: 'Směny',
        icon: ClockIcon,
        current: false,
        slug: 'shifts',
        submenu: [
          {
            name: 'Kalendář směn',
            link: '/smeny',
            current: false,
          },
          {
            name: 'Šablony směn',
            link: '/smeny/sablony',
            current: false,
          },
        ],
      },
      {
        key: 'smlouvy',
        name: 'Smlouvy',
        link: '/smlouvy',
        icon: DocumentTextIcon,
        current: false,
        slug: 'employee_contracts',
      },
      {
        key: 'zivotopisy',
        name: 'Životopisy',
        link: '/zivotopisy',
        icon: DocumentIcon,
        current: false,
        slug: 'biographies',
      },
    ],
  },
  {
    key: 'settings',
    title: 'Nastavení a správa',
    menu: [
      {
        key: 'users',
        name: 'Administrátoři',
        icon: UsersIcon,
        current: false,
        slug: 'users',
        submenu: [
          {
            name: 'Administrátoři',
            link: '/administratori',
            current: false,
          },
          {
            name: 'Skupiny a oprávnění',
            link: '/administratori/skupiny',
            current: false,
          },
        ],
      },
      {
        key: 'sites',
        name: 'Stránky',
        link: '/nastaveni/stranky',
        icon: GlobeAltIcon,
        current: false,
        slug: 'sites',
      },
      {
        key: 'filemanagers',
        name: 'Filemanager',
        link: '/nastaveni/filemanager',
        icon: PhotoIcon,
        current: false,
        slug: 'filemanagers',
      },
      {
        key: 'service_booking_settings',
        name: 'Nastavení rezervací',
        link: '/nastaveni/rezervace',
        icon: ClockIcon,
        current: false,
        slug: 'service_booking_settings',
      },
      {
        key: 'settings',
        name: 'Nastavení',
        link: '/nastaveni',
        icon: CogIcon,
        current: false,
        slug: 'settings',
      },
      {
        key: 'changelogs',
        name: 'Changelog',
        link: '/nastaveni/changelog',
        icon: CodeBracketIcon,
        current: false,
        slug: 'changelogs',
      },
      {
        key: 'activities',
        name: 'Aktivity',
        link: '/nastaveni/aktivity',
        icon: ChartBarSquareIcon,
        current: false,
        slug: 'activities',
      },
      {
        key: 'tax_rates',
        name: 'Sazby DPH',
        link: '/nastaveni/dph',
        icon: DocumentCurrencyEuroIcon,
        current: false,
        slug: 'tax_rates',
      },
      {
        key: 'languages',
        name: 'Jazyky',
        link: '/nastaveni/jazyky',
        icon: LanguageIcon,
        current: false,
        slug: 'languages',
      },
      {
        key: 'countries',
        name: 'Země',
        link: '/nastaveni/zeme',
        icon: GlobeEuropeAfricaIcon,
        current: false,
        slug: 'countries',
      },
      {
        key: 'currencies',
        name: 'Měny',
        link: '/nastaveni/meny',
        icon: CurrencyEuroIcon,
        current: false,
        slug: 'currencies',
      },
      {
        key: 'emails',
        name: 'E-maily',
        link: '/nastaveni/logy/emaily',
        icon: AtSymbolIcon,
        current: false,
        slug: 'emails',
      },
    ],
  },
];
